"""OGE executive-branch 278-T (periodic transaction report) scraper.

Source: OGE public disclosure system at extapps2.oge.gov (Domino). The
PAS+Index view exposes JSON via ?ReadViewEntries&OutputFormat=JSON: category
rows are officials ("Name, Agency, Position"), child rows are filings with a
direct PDF href and a label; "278 Transaction (MM/DD/YYYY)" marks periodic
transaction reports. PDFs are generated by Integrity.gov and share one text
layout: numbered rows of description / Purchase|Sale|Exchange / date / Yes|No
(over-30-days) / statutory amount range, with descriptions and amounts
wrapping across physical lines - parsed with the same record-joining approach
as the House PTR parser (validated against real filings).
"""
import datetime as dt
import json
import logging
import re
import time

import pdfplumber
import io
import requests

from db import get_conn
from scraper.common import finish_run, parse_amount_range, start_run

BASE = "https://extapps2.oge.gov/201/Presiden.nsf"
INDEX_URL = BASE + "/PAS+Index?ReadViewEntries&OutputFormat=JSON&ExpandView&Start={start}&Count=300"
log = logging.getLogger("oge")

HREF_RE = re.compile(r"href='([^']+)'")
LABEL_RE = re.compile(r">([^<]+)</a>")
POSTED_RE = re.compile(r"\((\d{2}/\d{2}/\d{4})\)")

OGE_START = re.compile(r"^\d{1,3}\s+.+?(?:Purchase|Sale|Exchange)\s+\d{2}/\d{2}/\d{4}\s+(?:Yes|No)\b")
OGE_CORE = re.compile(
    r"^(?P<n>\d{1,3})\s+(?P<pre>.+?)\s+(?P<ttype>Purchase|Sale|Exchange)\s+"
    r"(?P<tdate>\d{2}/\d{2}/\d{4})\s+(?P<over30>Yes|No)\s*(?P<rest>.*)$")
DOL = re.compile(r"\$[\d,]+")
OVR = re.compile(r"Over\s+\$[\d,]+", re.I)
TICK = re.compile(r"\(([A-Z][A-Z0-9.\-]{0,9})\)")
FURNITURE = ("# DESCRIPTION", "RECEIVED OVER", "30 DAYS AGO", "- Page ",
             "Periodic Transaction Report |", "Endnotes", "Data Revised")


def _mmddyyyy(raw):
    try:
        return dt.datetime.strptime((raw or "").strip(), "%m/%d/%Y").date()
    except ValueError:
        return None


def _entry_text(e):
    out = []
    for c in e.get("entrydata", []):
        t = c.get("text")
        if isinstance(t, dict):
            out.append(str(t.get("0", "")))
        elif t is not None:
            out.append(str(t))
    return " ".join(out)


def _iter_index(s):
    """Yield (official_dict|None, filing_dict|None) rows across pages."""
    start = 1
    while True:
        r = s.get(INDEX_URL.format(start=start), timeout=90)
        r.raise_for_status()
        d = json.loads(r.text)
        batch = d.get("viewentry", [])
        if not batch:
            return
        for e in batch:
            txt = _entry_text(e)
            if txt.startswith("[<div"):
                href_m = HREF_RE.search(txt)
                label_m = LABEL_RE.search(txt)
                if not href_m or not label_m:
                    continue
                label = label_m.group(1).strip()
                posted = POSTED_RE.search(label)
                yield None, {
                    "unid": e.get("@unid", ""),
                    "href": href_m.group(1),
                    "label": label,
                    "posted": _mmddyyyy(posted.group(1)) if posted else None,
                }
            elif txt.strip():
                parts = [p.strip() for p in txt.split(",")]
                yield {
                    "name": ", ".join(parts[:2]) if len(parts) >= 2 else txt.strip(),
                    "agency": parts[2] if len(parts) > 2 else None,
                    "position": ", ".join(parts[3:]) or None if len(parts) > 3 else None,
                }, None
        if len(batch) < 300:
            return
        start += len(batch)


def _parse_278t(text):
    records, cur = [], None

    def flush():
        nonlocal cur
        if cur:
            records.append(cur)
            cur = None

    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if any(f in line for f in FURNITURE) or line == "Transactions":
            flush()
            continue
        if OGE_START.match(line):
            flush()
            cur = [line]
        elif cur is not None:
            cur.append(line)
    flush()

    trades, misses = [], 0
    for rec in records:
        m = OGE_CORE.match(" ".join(rec))
        if not m:
            misses += 1
            continue
        rest = m.group("rest") or ""
        over = OVR.search(rest)
        dollars = DOL.findall(rest)
        if over:
            amt = over.group(0)
        elif len(dollars) >= 2:
            amt = f"{dollars[0]} - {dollars[1]}"
        elif dollars:
            amt = dollars[0]
        else:
            misses += 1
            continue
        asset = re.sub(r"\s+", " ", (m.group("pre") + " " + DOL.sub(" ", OVR.sub(" ", rest)).replace(" - ", " "))).strip(" -")
        tk = TICK.search(asset)
        trades.append({
            "row_num": int(m.group("n")),
            "transaction_date": _mmddyyyy(m.group("tdate")),
            "transaction_type": m.group("ttype"),
            "ticker": tk.group(1) if tk else None,
            "asset_name": asset,
            "amount_range": amt,
            "over_30_days": m.group("over30") == "Yes",
        })
    if trades and misses == 0:
        return trades, "parsed"
    if trades:
        return trades, "partial"
    return [], "unparseable"


def run(cfg):
    run_id = start_run("oge")
    new_filings, new_trades, errors = 0, 0, []
    parser_version = cfg.get("parser_version", "unknown")
    delay = float(cfg.get("request_delay_seconds", "0.5"))
    max_pdfs = int(cfg.get("oge_max_pdfs_per_run", "150"))
    s = requests.Session()
    s.headers.update({"User-Agent": cfg.get("edgar_user_agent", "congress-trades/1.0")})
    try:
        current = {}
        for official, filing in _iter_index(s):
            if official:
                current = official
                continue
            if not filing or "278 Transaction" not in filing["label"]:
                continue
            url = filing["href"] if filing["href"].startswith("http") else "https://extapps2.oge.gov" + filing["href"]
            with get_conn() as conn:
                with conn.cursor() as cur:
                    cur.execute(
                        """insert into oge_filings
                             (unid, official_name, agency, position, report_label,
                              posted_date, source_url, parse_status, scrape_run_id)
                           values (%s,%s,%s,%s,%s,%s,%s,'pending',%s)
                           on conflict (unid) do nothing returning id""",
                        (filing["unid"], current.get("name", "?"), current.get("agency"),
                         current.get("position"), filing["label"], filing["posted"], url, run_id),
                    )
                    if cur.fetchone():
                        new_filings += 1
        with get_conn() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """select id, source_url from oge_filings
                       where parse_status = 'pending'
                       order by posted_date desc nulls last limit %s""",
                    (max_pdfs,),
                )
                pending = cur.fetchall()
        for f in pending:
            try:
                time.sleep(delay)
                r = s.get(f["source_url"], timeout=120)
                r.raise_for_status()
                with pdfplumber.open(io.BytesIO(r.content)) as pdf:
                    text = "\n".join(p.extract_text() or "" for p in pdf.pages)
                trades, status = _parse_278t(text) if text.strip() else ([], "unparseable")
                with get_conn() as conn:
                    with conn.cursor() as cur:
                        for t in trades:
                            low, high = parse_amount_range(t["amount_range"])
                            cur.execute(
                                """insert into oge_trades
                                     (filing_id, row_num, transaction_date, transaction_type,
                                      ticker, asset_name, amount_range, amount_low, amount_high,
                                      over_30_days, source_url, parser_version)
                                   values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
                                (f["id"], t["row_num"], t["transaction_date"], t["transaction_type"],
                                 t["ticker"], t["asset_name"], t["amount_range"], low, high,
                                 t["over_30_days"], f["source_url"], parser_version),
                            )
                            new_trades += 1
                        cur.execute("update oge_filings set parse_status=%s where id=%s", (status, f["id"]))
            except Exception as e:
                errors.append(f"{f['id']}: {e}")
                with get_conn() as conn:
                    with conn.cursor() as cur:
                        cur.execute(
                            "update oge_filings set parse_status='unparseable', parse_error=%s where id=%s",
                            (str(e)[:500], f["id"]),
                        )
        finish_run(run_id, new_filings, new_trades, errors, "ok")
    except Exception as e:
        log.exception("oge run failed")
        errors.append(str(e))
        finish_run(run_id, new_filings, new_trades, errors, "failed")
    return {"new_filings": new_filings, "new_trades": new_trades, "errors": errors}
